name: Run coverage on PR
on:
    pull_request

jobs: 
    build-and-run-coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm i
            
            - name: Build Code
              run: npm run build
            
            - name: Run test and coverage
              run: npm run coverage

